WELCOME : '私は浮け鳥。あなたはだあれ？'
ASK_NAME : 'ねえねえ。あなたはだあれ？'
NAME2 : '名前はもう聞いたよ'
GET_NAME : 'さんだね。おっけー。ごしゅじん様につなぐからちょっと待ってね'
SHOW : 'ありがとう、LINE PAY で支払いするから、ちょっと待ってね'
SHOW_AGAIN : '読み取れなかったよお。もう一度カメラにQRをかざして、かざしたよ。と言ってね'
COMPLETE : 'ありがとう、確認するからちょっと待ってね'
TELL : '、また来るんだね。伝えておくね。ありがとう'
DEFAULT : 'なんて言ってるか、わからないよお'
