SNAP_SHOT: 'hogehoge'
LINE_PAY: 'fugafuga'
POST: 'https://api.line.me/v2/bot/message/push'
PUSH_URL: 'https://api.line.me/v2/bot/message/push'
RASPI2: 'https://b66deb0b.ngrok.io'
TEMPLETE : "http://example.com/page/123"
QR2URL : 'https://2e7d3eeb.ngrok.io/qr2url'
