HORN: 'https://shop.r10s.jp/book/cabinet/4798/4900459524798_2.jpg'
OKAERI: 'https://matsuko.link/img/okaeri.jpg'
SNAP_SHOT: 'https://f1117ee8.ngrok.io/image.jpg'
TEMPLATE_RESPONSE: 'https://example.com/bot/images/item1.jpg'
