LOGIN_SUCCESS : '認証に成功しました！name:ここに登録名を入力　の形式で名前を入力して下さい'
LOGIN_FALSE : '認証に失敗しました。再度入力して下さい'
PLESE_NAME : 'name:ここに登録名を入力 の形式で名前を入力して下さい'
TO_ADMIN : '管理者に伝えておきました、パスワードの通知をお待ちください'
PLESE_PASS : '登録が完了するまでは機能は使えません'
